### ISSUE TITLE
Manufacturer ID is not working if not Intel?

### ISSUE THREAD

**Issue by Torinde** [gsuberland/web-cpuid#2]
Great tool! Exactly what I [was searching for](https://github.com/InstLatx64/InstLatx64/issues/9) at InstLatx64.

The CPUID Dump format is slightly different, so an alignment between the two projects would be nice to have. Maybe even with a link between them, so that user doesn't have to copy-paste.

Now, about web-cpuid:
- Manufacturer ID - doesn't work, I have to keep it "GenuineIntel" in order for all the rest to load
- Processor Brand String and Manufacturer ID - would be good also to show the full text combined in a human readable form, in addition to the chunks on separate lines.
- MPX/AVX512 state - 00h [green] instead of false (0) [red] ?
![image](https://github.com/gsuberland/web-cpuid/assets/97228894/2b9b1bf9-cfd1-44f2-a331-d595c594771a)

**Comment by gsuberland** [comment]
AMD decoding is WIP; I've got a partial implementation of it locally but it's not finished yet.

Grouped metadata is something I'm planning, but requires some overhaul of the frontend presentation logic so it'll take a bit of effort. Displaying things like the full brand string hinges on this.

Good point on the XCR0 state colours. This happens because multi-bit fields are just seen as numbers in the rendering code, so 0 is "valid" and therefore green. Searching the InstLatX64 data, it looks like the only correct values are all-0 or all-1 (presumably because if MPX/AVX512 state is available it always consumes 2 and 3 subleaves respectively) so that should be easy to implement as an enum.

**Comment by gsuberland** [comment]
The XCR0 state data, among other things, has been fixed in 341a15e.

**Comment by gsuberland** [comment]
Vendor and brand string summary decoding is added in 7809e7f. 

I've opened #3 to track the AMD CPUID decoding work.

**Comment by Torinde** [comment]
> AMD decoding is WIP

Besides Intel/AMD, there are other vendor-specific parts for [Centaur, etc.](https://github.com/InstLatx64/InstLatx64/issues/9#issuecomment-2104781568)

**Comment by gsuberland** [comment]
Those are currently out of scope for this project; I just don't have time to work on them.
